# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Engineor's Lab 
subtitle: That's what we do!

# disqus shortname
disqus:
    shortname: lab-engineor
